# Generated by Django 4.2.7 on 2023-11-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('png_file', models.ImageField(upload_to='media/png/')),
                ('jpg_file', models.ImageField(upload_to='media/jpg/')),
                ('svg_file', models.ImageField(upload_to='media/svg/')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.logo')),
            ],
        ),
        migrations.CreateModel(
            name='LogoVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('usage', models.TextField(blank=True, null=True)),
                ('png_file', models.ImageField(blank=True, upload_to='media/png/')),
                ('jpg_file', models.ImageField(blank=True, upload_to='media/jpg/')),
                ('svg_file', models.ImageField(blank=True, upload_to='media/svg/')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='core.logo')),
            ],
        ),
    ]
